# 头部菜单，title: link
menu:
  首页: /
  分类: /categories
  标签: /tags
  归档: /archives  
  关于: /about

# 是否显示目录
TOC: false

# 是否自动播放音乐
autoplay: false

# 默认音乐（随机播放）
mp3: 
    - http://link.hhtjim.com/163/425570952.mp3
    - http://link.hhtjim.com/163/425570952.mp3

# 首页封面图, 为空时取文章的cover作为封面(注意跨域问题,建议使用同源图片)
#welcome_cover: /img/index.jpg
welcome_cover: /coveri/
#首页封面图随机产生的总数 起始为101.jpg 增加照片时更改该数值 照片必须是数字.jpg格式，数字不可中断 尽量截取1920*1080的图片
welcome_cover_count: 3
# 默认文章封面图（随机调用,支持外链）680*440大小
cover: 
  - /img/cover.jpg
  - /img/welcome-cover.jpg

 
# 是否使用mathjax
mathjax: false


# 是否关闭默认滚动条
scrollbar: true

# 本地搜索,请将索引文件放在网站根目录,或修改主题js文件的path值
local_search:
    # 是否启用
    enable: false

# 是否显示 一言(hitokoto)
hitokoto: true

# 链接(可选:facebook,twitter,github,wechat,email)
links:
    facebook: /
    twitter: /
    github: /
    wechat: /img/logo.png
    email: mailto:xxxx@gmail.com
  
# 备案
beian: 
    # 是否显示备案信息
    enable: true
    # 是否在主页面最底下显示备案信息(虽然丑，但是完全满足规定要求)
    enableFooter: true
    # 备案号
    beianInfo: 冀ICP备xxxxxxx号
    # 链接地址
    link: http://www.beian.miit.gov.cn
    #公安备案信息
    gaicon: /img/gongan.png
    #公安网址
    galink: http://www.beian.gov.cn/portal/registerSystemInfo?recordcode=*****
    #公安备案号
    gabeianInfo: *公网安备 ******号

# Gitalk 评论插件（https://github.com/gitalk/gitalk）
gitalk:
    # 是否启用评论功能
    enable: false
    # 是否自动展开评论框
    autoExpand: false
    # 应用编号
    clientID: ''
    # 应用秘钥
    clientSecret: ''
    # issue仓库名
    repo: ''
    # Github名
    owner: ''
    # Github名
    admin: ['']
    # Ensure uniqueness and length less than 50
    id: location.pathname
    # Facebook-like distraction free mode
    distractionFreeMode: false

# 网站关键字
keywords: keep0

# 使用google_analytics进行统计的话，需要配置ID
google_analytics: tryry

# 网站ico
favicon: /img/favicon.png

# rss文件
rss: atom.xml
